jobs:
- job: Windows

  pool:
    name: Hosted
    
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false
    
  - task: GitVersion@4
    # Ignore gitversion for forks, until this is fixed:
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      updateAssemblyInfo: false

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.103'

  - task: DotNetCoreCLI@2
    displayName: .NET Core Build
    inputs:
      command: build
      arguments: --configuration Release  "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "-p:PackageVersion=$(GITVERSION.FullSemVer)" "/p:InformationalVersion=$(GITVERSION.InformationalVersion)" /detailedsummary
      workingDirectory: $(build.sourcesdirectory)\src

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.504'

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno.PackageDiff"
      SignPackageDescription: "Uno.PackageDiff"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: unosourcegenerator-drop
      ArtifactType: Container
            
  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*tests.dll
        !**\obj\**
      vstestLocationMethod: version
      vsTestVersion: latest
      testSelector: testAssemblies

- job: Linux
  workspace:
    clean: all

  pool:
    name: Default
    demands:
    - agent.os -equals Linux
    
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.103'

  - task: DotNetCoreCLI@2
    displayName: .NET Core Build
    inputs:
      command: build
      arguments: --configuration Release /detailedsummary
      workingDirectory: $(build.sourcesdirectory)/src

- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)/.nuget
    SourceLinkEnabled: false

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.103'

  - task: DotNetCoreCLI@2
    displayName: .NET Core Build
    inputs:
      command: build
      arguments: --configuration Release /detailedsummary
      workingDirectory: $(build.sourcesdirectory)/src
