trigger:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

pr:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

jobs:
- job: Windows

  pool:
    vmImage: 'windows-2022'

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - checkout: self
    clean: true

  - pwsh: |
      dotnet tool uninstall nbgv -g
      dotnet tool install nbgv -g --version 3.6.139
      nbgv cloud -a
    displayName: Version with NBGV
    name: NBGV

  - pwsh: |
      $InformationalVersion="$(NBGV_SemVer2)+$(NBGV_GitCommitId)-$(NBGV_BuildingRef)".Replace("refs/heads/","").Replace("/","-")
      echo "##vso[task.setvariable variable=NBGV_InformationalVersion;]$InformationalVersion"
      echo "##vso[task.setvariable variable=NBGV_InformationalVersion;isOutput=true;]$InformationalVersion"
      echo "Informational Version: $InformationalVersion"

    displayName: Generate Informational Version
    name: NBGV_InformationalVersion

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    retryCountOnTaskFailure: 3
    inputs:
      packageType: sdk
      version: 9.0.200

  - pwsh: |
      cd src/Uno.UITest.Helpers
      dotnet build -c Release /p:PackageVersion=$(NBGV_SemVer2) /p:InformationalVersion=$(NBGV_InformationalVersion) /p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget
    displayName: 'Build packages'

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno.PackageDiff"
      SignPackageDescription: "Uno.PackageDiff"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-uitest-drop
      ArtifactType: Container

- job: Wasm_UITests

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    retryCountOnTaskFailure: 3
    inputs:
      packageType: sdk
      version: 9.0.200

  - template: build/templates/dotnet-install-linux.yml
    parameters:
      # android SDK is skipped because we're installing it in the test script
      UnoCheckParameters: '--tfm net9.0-browserwasm'

  - bash: |
      chmod +x build/wasm-uitest-run.sh
      build/wasm-uitest-run.sh

    env:
      GIT_TARGETBRANCH: "$(System.PullRequest.TargetBranch)"
      GIT_SOURCEBRANCH: "$(Build.SourceBranch)"
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      BUILD_ARTIFACTSTAGINGDIRECTORY: "$(build.artifactstagingdirectory)"

    displayName: 'Running build'

  - task: PublishTestResults@2
    inputs:
      testRunTitle: 'WebAssembly Test Run'
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(build.artifactstagingdirectory)/test-results/uitest-wasm.xml'
      failTaskOnFailedTests: true
      searchFolder: '$(System.DefaultWorkingDirectory)' # https://github.com/microsoft/azure-pipelines-tasks/issues/10072

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-uitest-tests
      ArtifactType: Container

- job: Android_Tests
  variables:
    CI_Build: true
    SourceLinkEnabled: false

  pool:
    vmImage: 'macOS-14'

  steps:
  - checkout: self
    clean: true

  - template: build/templates/dotnet-install-mac.yml
    parameters:
      UnoCheckParameters: '--tfm net9.0-android --skip androidsdk'

  - bash: |
      chmod +x $(build.sourcesdirectory)/build/android-uitest-run.sh
      $(build.sourcesdirectory)/build/android-uitest-run.sh

    displayName: Build and Run Android Tests

    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      BUILD_ARTIFACTSTAGINGDIRECTORY: "$(build.artifactstagingdirectory)"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunTitle: 'Android Test Run'
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(build.sourcesdirectory)/build/TestResult.xml'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-uitest-tests
      ArtifactType: Container

- job: iOS_Tests
  variables:
    CI_Build: true
    SourceLinkEnabled: false
    XCODE_ROOT: /Applications/Xcode_16.2.app

  pool:
    vmImage: 'macOS-14'

  steps:
  - checkout: self
    clean: true

  - template: build/templates/dotnet-install-mac.yml
    parameters:
      UnoCheckParameters: '--tfm net9.0-ios'

  - bash: /bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'${XCODE_ROOT};sudo xcode-select --switch ${XCODE_ROOT}/Contents/Developer"
    displayName: Select Xcode

  - bash: |
      chmod +x $(build.sourcesdirectory)/build/ios-uitest-run.sh
      $(build.sourcesdirectory)/build/ios-uitest-run.sh

    displayName: Build and Run iOS Test

    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      BUILD_ARTIFACTSTAGINGDIRECTORY: "$(build.artifactstagingdirectory)"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunTitle: 'iOS Test Run'
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(build.sourcesdirectory)/build/TestResult.xml'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-uitest-tests
      ArtifactType: Container
