using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Uno.UITest.Selenium.Models
{

	// Models generated by json2csharp.com from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
	public class Chrome
	{
		[JsonPropertyName("platform")]
		public string Platform { get; set; }

		[JsonPropertyName("url")]
		public string Url { get; set; }
	}

	public class Chromedriver
	{
		[JsonPropertyName("platform")]
		public string Platform { get; set; }

		[JsonPropertyName("url")]
		public string Url { get; set; }
	}

	public class Downloads
	{
		[JsonPropertyName("chrome")]
		public Chrome[] Chrome { get; set; }

		[JsonPropertyName("chromedriver")]
		public Chromedriver[] Chromedriver { get; set; }
	}

	public class Root
	{
		[JsonPropertyName("timestamp")]
		public DateTime? Timestamp { get; set; }

		[JsonPropertyName("versions")]
		public ChromeVersion[] Versions { get; set; }
	}

	public class ChromeVersion
	{
		[JsonPropertyName("version")]
		public string Version { get; set; }

		[JsonPropertyName("revision")]
		public string Revision { get; set; }

		[JsonPropertyName("downloads")]
		public Downloads Downloads { get; set; }
	}

}
